import { Property, Vendor } from './types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    name: 'Ocean View Villa',
    address: '123 Seaside Drive',
    city: 'Miami',
    state: 'FL',
    type: 'villa',
    bedrooms: 4,
    bathrooms: 3,
    nightlyRate: 450,
    status: 'available',
    assignedVendorIds: ['vendor-1', 'vendor-2'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prop-2',
    name: 'Mountain Cabin Retreat',
    address: '45 Pine Ridge Rd',
    city: 'Aspen',
    state: 'CO',
    type: 'cabin',
    bedrooms: 3,
    bathrooms: 2,
    nightlyRate: 320,
    status: 'occupied',
    assignedVendorIds: ['vendor-1', 'vendor-3'],
    createdAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'prop-3',
    name: 'Downtown Loft',
    address: '789 Main St, Unit 4B',
    city: 'Nashville',
    state: 'TN',
    type: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    nightlyRate: 185,
    status: 'maintenance',
    assignedVendorIds: ['vendor-2', 'vendor-4'],
    createdAt: '2024-03-05T14:00:00Z',
  },
  {
    id: 'prop-4',
    name: 'Beachfront Condo',
    address: '55 Gulf Blvd',
    city: 'Clearwater',
    state: 'FL',
    type: 'condo',
    bedrooms: 2,
    bathrooms: 2,
    nightlyRate: 275,
    status: 'available',
    assignedVendorIds: ['vendor-1'],
    createdAt: '2024-03-20T11:00:00Z',
  },
  {
    id: 'prop-5',
    name: 'Lakeside House',
    address: '12 Lakeview Ln',
    city: 'Lake Tahoe',
    state: 'CA',
    type: 'house',
    bedrooms: 5,
    bathrooms: 4,
    nightlyRate: 550,
    status: 'occupied',
    assignedVendorIds: ['vendor-3', 'vendor-5'],
    createdAt: '2024-04-01T08:00:00Z',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Sparkling Clean Co.',
    email: 'info@sparklingclean.com',
    phone: '(305) 555-0101',
    specialty: 'cleaning',
    status: 'active',
    assignedPropertyIds: ['prop-1', 'prop-2', 'prop-4'],
    rating: 4.9,
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: 'vendor-2',
    name: 'FixIt Pro Maintenance',
    email: 'service@fixitpro.com',
    phone: '(615) 555-0202',
    specialty: 'maintenance',
    status: 'active',
    assignedPropertyIds: ['prop-1', 'prop-3'],
    rating: 4.7,
    createdAt: '2023-11-15T10:00:00Z',
  },
  {
    id: 'vendor-3',
    name: 'GreenThumb Landscaping',
    email: 'hello@greenthumb.com',
    phone: '(970) 555-0303',
    specialty: 'landscaping',
    status: 'active',
    assignedPropertyIds: ['prop-2', 'prop-5'],
    rating: 4.8,
    createdAt: '2023-12-01T10:00:00Z',
  },
  {
    id: 'vendor-4',
    name: 'WireWise Electric',
    email: 'contact@wirewise.com',
    phone: '(615) 555-0404',
    specialty: 'electrical',
    status: 'active',
    assignedPropertyIds: ['prop-3'],
    rating: 4.6,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'vendor-5',
    name: 'AquaFlow Plumbing',
    email: 'service@aquaflow.com',
    phone: '(530) 555-0505',
    specialty: 'plumbing',
    status: 'inactive',
    assignedPropertyIds: ['prop-5'],
    rating: 4.3,
    createdAt: '2024-02-01T10:00:00Z',
  },
];
